version: "3.7"
services:
  db:
    image: mysql:8
    volumes:
    - ../sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucon2021_prior
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
